export { default as Home } from "./metrics/metrics.vue";
export { default as Announcements } from "./announcements/announcements.vue";
export { default as Students } from "./students/students.vue";
export { default as Teachers } from "./teachers/teachers.vue";
export { default as Schools } from "./schools/schools.vue";
export { default as Chatroom } from "./chatroom/chatroom.vue";
export { default as Mentors } from "./mentors/mentors.vue";
export { default as BlogPosts } from "./blog posts/blogs.vue";
export { default as Books } from "./resources/books/books.vue";
export { default as Papers } from "./resources/papers/papers.vue";
export { default as Videos } from "./resources/videos/videos.vue";
export { default as Quizes } from "./resources/quizes/quizes.vue";
export { default as Quiz } from "./resources/quizes/quiz.vue";
export { default as Summaries } from "./resources/summaries/summaries.vue";
export { default as Modules } from "./accessories/modules/modules.vue";
export { default as Combinations } from "./accessories/cominations/combinations.vue";
export { default as PrivateLibary } from "./accessories/private library/library.vue";
export { default as AdminProfile } from "./profile/profile.vue";
